name : Generate ACSII

on : push

jobs:
    Generate_ASCII:
        runs-on: ubuntu-latest
        steps:
            - name: Check out Repo
              uses: actions/checkout@v4

            - name: Install CowSay program
              run: sudo apt-get install cowsay -y

            - name: Execute CowSay program
              run: cowsay -f dragon "Run for your live! I am a Dragon! Roar!!!" >> dragon.txt

            - name: Test file exists
              run: grep -i "dragon" dragon.txt
 
            - name: Read dragon.txt file
              run: cat dragon.txt

            - name: List repo files
              run: ls -al