name : Lab1

on:
    schedule:
        - cron: '*/5 * * * *'   # <=== Change this value

jobs:
  HelloJob: 
    runs-on: ubuntu-latest
    steps:
        - name: Echo Text
          run: echo "Hello, Shandra"