name : Lab1

on: workflow_dispatch
    

jobs:
  HelloJob1: 
    runs-on: ubuntu-latest
    steps:
        - name: Echo Text
          run: |
            sleep 20
            echo "1Hello, Shandra"
  
  HelloJob2: 
    runs-on: ubuntu-latest
    steps:
        - name: Echo Text
          run: |
            sleep 10
            echo "2Hello, Shandra"