name : Matrix

on: push
    #workflow_dispatch #a manual workflow trigger

jobs:
    deploy:
      #if the branch is the main branch.
      if: github.ref == 'refs/heads/main'  
      strategy: 
       fail-fast: false #will allow the other jobs to continue to run instead of canceling them. True, default
       max-parallel: 2  #will only run max two jobs at a time.
       matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        images: [hello-world, alpine]
        # exclude: don't run the image on that os
        exclude: 
          - images: alpine
            os: windows-latest
        # include:  do run that image on that os.    
        include: 
          - images: amd64/alpine
            os: ubuntu-20.04
      runs-on: ${{ matrix.os }}
      steps:
      - name: Echo Docker Details
        run: docker info
                        
      - name: Run image on ${{ matrix.os }}
        run: |
          #timeout-minutes: 1
          docker run ${{matrix.images}}