name : Matrix

on: push
    #workflow_dispatch #a manual workflow trigger

jobs:
    deploy:
      strategy: 
       matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        images: [hello-world, alpine]
      runs-on: ${{ matrix.os }}
      steps:
      - name: Echo Docker Details
        run: docker info
                        
      - name: Run image on ${{ matrix.os }}
        run: docker run ${{matrix.images}}