name : Multiple Jobs

on : push

jobs:
  task_1: 
    runs-on: ubuntu-latest
    steps:
        - name: Install CowSay program
          run: sudo apt-get install cowsay -y

        - name: Execute CowSay program
          run: cowsay -f dragon "Run for your live! I am a Dragon! Roar!!!" >> dragon.txt
       
        - name: dragon-file-upload
          uses: actions/upload-artifact@v4
          with:
            name: DragonFile
            path: dragon.txt
            if-no-files-found: error    # 'warn' or 'ignore' are also available, defaults to `warn`

  task_2:
    needs: task_1  
    runs-on: ubuntu-latest
    steps:
        - name: dragon-file-download
          uses: actions/download-artifact@v4
          with:
            name: DragonFile
            path: dragon.txt
            #if-no-files-found: error    # 'warn' or 'ignore' are also available, defaults to `warn`

        - name: Test file exists
          run: ls | grep -w 'dragon.txt'

            
  task_3:
    needs: task_2
    runs-on: ubuntu-latest
    steps:
        - name: dragon-file-download
          uses: actions/download-artifact@v4
          with:
            name: DragonFile
            path: dragon.txt
            #if-no-files-found: error    # 'warn' or 'ignore' are also available, defaults to `warn`

        - name: Read dragon.txt file
          run: cat dragon.txt
        - name: Deploying
          run: echo "Deploying........"