name : Multiple Jobs

on : push

jobs:
  task_1: 
    runs-on: ubuntu-latest
    steps:
        - name: Install CowSay program
          run:  |
            pwd
            ls -al
            sudo apt-get install cowsay -y

        - name: Execute CowSay program
          run: |
            pwd
            cowsay -f dragon "Run for your live! I am a Dragon! Roar!!!" >> ./dragon.txt
            ls -al
            sleep 5

        - name: dragon-file-upload
          uses: actions/upload-artifact@v4
          with:
            name: DragonFile
            path: dragon.txt
            if-no-files-found: error    # 'warn' or 'ignore' are also available, defaults to `warn`

  task_2:
    needs: task_1  
    runs-on: ubuntu-latest
    steps:
        - name: dragon-file-download
          uses: actions/download-artifact@v4
          with:
            name: DragonFile
            path: dragon.txt
            
        - name: Test file exists
          run: |
            pwd
            ls -al
            grep -i "dragon" dragon.txt
            #ls | grep -w 'dragon.txt'
            ls -al
            
  task_3:
    needs: task_2
    runs-on: ubuntu-latest
    steps:
        - name: dragon-file-download
          uses: actions/download-artifact@v4
          with:
            name: DragonFile
            path: dragon.txt
            
        - name: Read dragon.txt file
          run: |
            ls -al 
            cat dragon.txt
            ls -al
        - name: Deploying
          run: echo "Deploying........"