name:  Python Matrix

on: push

jobs:
    build:
      strategy: 
       matrix:
         os: [ubuntu-latest, ubuntu-20.04, windows-latest]
         images: ["python:3.10", "python:3.11","python:latest" ]
        # #exclude: don't run the image on that os
         exclude: 
         - images: "python:3.11"
           os: windows-latest
        # # include:  do run that image on that os.    
         include: 
         - images: winamd64/python
           os: winamd64
      runs-on: ${{ matrix.os }}
      steps:
      - name: Echo Python Images
        run: docker info
                        
      - name: Install Python on ${{ matrix.os }}
        run: docker run ${{matrix.images}}