name : Run Shell Script

on : push

jobs:
   _RunShellScript:
        runs-on: ubuntu-latest
        steps:
            - name: Check out Repo
              uses: actions/checkout@v4

            - name: List files
              run: ls -al

            - name: Execute the shell script
              run: |
                chmod +x ./ascii_script.sh
                /.ascii_script.sh
                

