name : First WF

on : push

jobs:
    first_fw:
        runs-on: ubuntu-latest
        steps:
            - name: Check out Repo
              uses: actions/checkout@v4
              
            - name: Welcome Message
              run: echo "The first WF"

            - name: List files
              run:  ls

            - name: Read File
              run: cat README.md