name : First WF

on : push

jobs:
    first_fw:
        runs-on: ubuntu-latest
        steps:
            - name: Check out Repo
              uses: actions/checkout@v4

            - name: Welcome mesg, List and Read files
              run: |
                echo "The first WF"
                ls -al
                cat "README.md"
            # can run several cmd in the same step usin a pipe |

            - name: Generate ASCII Artwork
              run: echo "Run the CowSay program"

            # commented out steps below as listed in several steps
            # - name: List files
            #   run:  ls

            # - name: Read File
            #   run: cat README.md